# Generated by Django 3.2.7 on 2021-11-04 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultation_form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Konsultasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('npm', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('email', models.CharField(max_length=50)),
                ('selected_accept', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='consultation_form.consultation')),
            ],
        ),
    ]
