# Generated by Django 3.2.8 on 2021-10-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('npm', models.PositiveBigIntegerField()),
                ('date', models.DateField()),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
