# Generated by Django 3.2.8 on 2021-10-31 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konfirmasi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Konsultasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('npm', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Consultation',
        ),
    ]
