# Generated by Django 3.2.7 on 2021-12-22 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('konfirmasi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='konsultasi',
            name='selected_accept',
        ),
    ]
