# Generated by Django 3.2.8 on 2021-11-04 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_form', '0002_consultation_selected_counselor'),
        ('konfirmasi', '0002_auto_20211101_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='konsultasi',
            name='selected_accept',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='consultation_form.consultation'),
        ),
    ]
