# Generated by Django 3.2.7 on 2021-10-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nominal', models.CharField(max_length=50)),
                ('bukti', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
