# Generated by Django 3.2.7 on 2021-11-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_alter_donasi_nominal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donasi',
            old_name='bukti',
            new_name='bukti_Transfer',
        ),
        migrations.AlterField(
            model_name='donasi',
            name='nominal',
            field=models.CharField(choices=[('Rp50.000', 'Rp50.000'), ('Rp100.000', 'Rp100.000'), ('Rp250.000', 'Rp250.000'), ('Rp500.000', 'Rp500.000'), ('Rp1.000.000', 'Rp1.000.000')], default='Rp50.000', max_length=12),
        ),
    ]
