# Generated by Django 3.2.7 on 2021-11-04 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threader', '0002_thread_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-id']},
        ),
    ]
