# Generated by Django 3.2.7 on 2021-11-04 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threader', '0003_alter_thread_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='user',
        ),
    ]
