# Generated by Django 3.2.7 on 2021-11-05 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threader', '0004_remove_thread_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='thread',
            new_name='content',
        ),
    ]
