# Generated by Django 3.2.7 on 2021-11-05 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('threader', '0007_thread_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='date',
            new_name='timestamp',
        ),
        migrations.CreateModel(
            name='ThreadLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='threader.thread')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='thread',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='tweet_user', through='threader.ThreadLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
