# Generated by Django 3.2.7 on 2021-11-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threader', '0010_alter_thread_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
