# Generated by Django 3.2.7 on 2021-11-05 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threader', '0011_alter_thread_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='threader.thread'),
        ),
    ]
