# Generated by Django 3.2.7 on 2021-12-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biopsikolog',
            name='domisili',
            field=models.CharField(choices=[('Jakarta', 'jakarta'), ('Bogor', 'bogor'), ('Depok', 'depok'), ('Tangerang', 'tangerang'), ('Bekasi', 'bekasi')], default='Jakarta', max_length=9),
        ),
    ]
