# Generated by Django 3.2.7 on 2021-12-21 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_biopsikolog_domisili'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biopsikolog',
            name='domisili',
            field=models.CharField(choices=[('jakarta', 'Jakarta'), ('bogor', 'Bogor'), ('depok', 'Depok'), ('tangerang', 'Tangerang'), ('bekasi', 'Bekasi')], default='jakarta', max_length=9),
        ),
    ]
