# Generated by Django 3.2.7 on 2021-12-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_biopsikolog_domisili'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biopsikolog',
            name='domisili',
            field=models.CharField(choices=[('jakarta', 'jakarta'), ('bogor', 'bogor'), ('depok', 'depok'), ('tangerang', 'tangerang'), ('bekasi', 'bekasi')], default='jakarta', max_length=9),
        ),
    ]
