# Generated by Django 3.2.7 on 2021-12-21 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_biopsikolog_domisili'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biopsikolog',
            name='domisili',
            field=models.CharField(choices=[('Jakarta', 'Jakarta'), ('Bogor', 'Bogor'), ('Depok', 'Depok'), ('Tangerang', 'Tangerang'), ('Bekasi', 'Bekasi')], default='Jakarta', max_length=9),
        ),
    ]
