# Generated by Django 3.2.7 on 2021-12-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_article_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.TextField(),
        ),
    ]
